# Generated by Django 4.1.5 on 2023-03-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('ratings', models.DecimalField(decimal_places=1, max_digits=3)),
                ('netflix_link', models.CharField(max_length=255)),
            ],
        ),
    ]
